### ISSUE TITLE
HUP scripts do not take into account `balenaRootCA`

### ISSUE THREAD

**Issue by hedss** [balena-os/resinhup#213]
When attempting to HUP on a device served from an environment that is using self-signed CAs (such as an OnPrem not using 3rd party signed EECs), the script will fail because it uses `curl`.

`curl` tries to authenticate any HTTPS traffic via the system certstore, and the `balenaRootCA` `config.json` var is used _directly_ by those things that currently require it (the Supervisor and `os-config`).

We could either continue this by:

1. Reading the config var at startup, decoding to a specific new directory in `/tmp` and then using `--capath <tmpPath>` in the HUP script, appending the option to curl should it exist

2. Adding the encoded cert to the system cert store on startup

The first would mean fewer changes, as it just requires a change to `resin-proxy` HUP scripts.

The latter requires more work, as I suspect this would now require the certstore to become part of the state partition. Although in the long run, we could drop `os-config`'s knowledge of the the config var (although not the Supervisor, and it still needs to be passed the var to decode it in its own container).

**Comment by imrehg** [comment]
This was discussed, and the idea is to handle this on the OS side, thus no changes needed on the HUP side as much as I know @hedss

**Comment by hedss** [comment]
@imrehg No, it's all down to the OS adding certs to the cert store: https://github.com/balena-os/meta-balena/issues/1398

We can close this.
