### ISSUE TITLE
Improve UX for BETA device types

### ISSUE THREAD

**Issue by xginn8** [balena-os/resinhup#241]
Related to https://github.com/balena-io-modules/balena-hup-action-utils/issues/13, when working with a beta device type it was confusing why HUPs were disabled. We should improve the wording or UX generally to indicate that HUPs are disabled due to that beta restriction, and perhaps to contact support/fleetops to request upgrades if relevant. cc @imrehg

**Comment by imrehg** [comment]
@xginn8 the HUP scrip handles all device types, the issue there was in the UI, as much as I can tell, as the UI and the proxy are both gatekeeping here. Thus such issues are cross-component and should be opened in the product repo. Having said that, it's already fixed, just waiting for UI deploy, which is held up by other changes.
Thanks nonetheless, for the feedback!
